name: deploy-to-okteto
on:
  push:	
    branches:	
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup NodeJs Environment
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Bundle
      run: npm run bundle-for-docker
    - name: Deploy
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      uses: okteto/actions/build@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        tag: ${{ secrets.DOCKER_USERNAME }}/react-parcel-demo:${{ github.sha }}
      uses: okteto/actions/namespace@master
      id: namespace
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: dunmengjun
      uses: okteto/actions/deploy@master
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}  
      with:
        namespace: dunmengjun
        manifest: k8s.yml
        tag: ${{ secrets.DOCKER_USERNAME }}/react-parcel-demo:${{ github.sha }}
        waitOn: deployment/react-parcel-demo
