name: deploy-to-github-pages
on:
  push:	
    branches:	
      - master
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup NodeJs Environment
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Bundle
      run: npm run bundle-for-github-page
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build/github-page # The folder the action should deploy.
